routes:
  - method: GET
    source: /api/escooters/:id
    target: http://escooters-service:8080/escooters/

  - method: POST
    source: /api/escooters/
    target: http://escooters-service:8080/escooters/

